### ISSUE TITLE
Native linking failed

### ISSUE THREAD

**Issue by pablogupi** [CrossGeeks/GoogleClientPlugin#21]
**Describe the bug**
Hello
I add this plugin in my Xamarin Forms project and can't build my iOS project since then. These are the three errors:

 Error: no such file or directory: '.../obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/GoogleSignIn' (....iOS)
.../error MT5209: Error: clang: error: no such file or directory: '
.../obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/GoogleSignIn' (...iOS) Native linking
/.../MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (...iOS)

**To Reproduce**
1. Install plugin
2. Config Firebase project and copy GoogleService-Info.plist
3. Build project

**Expected behavior**
Build without errors  

**Desktop (please complete the following information):**
 - MacOsx Mojave
 - Rider 2018 and Visual Studio 2015

**Smartphone (please complete the following information):**
 - Device: [Simulator iPhone X Max 12.1, iPhone X 12.1 ]
 - OS: [iOS 12.1 ]

**Additional context**
My project contain CrossGeeks FacebookClientPlugin, FirebasePushNotificationPlugin and they work correctly

**Comment by Pujolsluis** [comment]
Hey @pablogupi ,

This issue is not directly related to a problem with the plugin, but its more about a missing xcode update you might need. you can read this blog post about this same issue https://askxammy.com/how-to-fix-native-linking-failed-error-in-xamarin-ios/ 

I'm glad you are looking forward to using the plugin on your projects, give this solution a try and keep me updated! 🙌😊

**Comment by Pujolsluis** [comment]
Hey @pablogupi ,

Mhmm, I would recommend searching up a little more about this problem since its a common issue sometimes on Xamarin iOS, and there are a few ways people have tried to solve it.

Here is another I found, simply add in your iOS Project this additional mtouch argument: 
--registrar:static

**Comment by Pujolsluis** [comment]
Will proceed to close this Issue, since there is no update on it.

**Comment by maxyhi** [comment]
Adding --registrar:static doesn't fix it, it instead outputs:

**Comment by maxyhi** [comment]
resolved the issue above by adding xamarin.firebase.ios.core 4.0.13.1 make sure the android version is using the same version as well

**Comment by Pujolsluis** [comment]
Great job @maxyhi!

Thanks for the Feedback, yes sometimes VS doesn't install all the dependencies correctly when you install nuggets so it's always good to verify if the nugget has what it needs to function properly.
