### ISSUE TITLE
Error:  There was a problem reading or writing to the application keychain.

### ISSUE THREAD

**Issue by edhalsim** [CrossGeeks/GoogleClientPlugin#30]
Hi,
I'm just now to the point where I'm trying to run my app. on the iPhoneSimulator on VS 2017.  My iMac is connected.  The app loads, but then when I click on the button to login to Google, I'm getting:
    Error:  There was a problem reading or writing to the application keychain.
It's blowing up on the LoginAsync method:

    public async void LoginAsync()
    {
        _googleClientManager.OnLogin += OnLoginCompleted;
        try
        {
            await _googleClientManager.LoginAsync();   <-- Blows up here
        }

I'd appreciate any help you can provide.  I'm still very new to mobile development so please bear with me.  Thanks.

**Comment by Pujolsluis** [comment]
Hey @edhalsim ,

I'm glad your looking forward to using the plugin this error is caused because of an incomplete setup on your project please make sure to follow all the guides step by step. You can find the solution to enabling keychain access in the following guide:

[Google Firebase Setup](https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/GoogleClient/docs/GoogleFirebaseConsoleSetup.md)

**Comment by ColdThor** [comment]
Having the same issue. Its working on Android, I completed all the steps in the tutorial. Maybe its doing it cause its not yet signed?

@edhalsim  have you fixed the issue?
