### ISSUE TITLE
[Error] android.view.WindowLeaked

### ISSUE THREAD

**Issue by JaeWLee** [CrossGeeks/GoogleClientPlugin#4]
I followed android tutorial and add google-services.json in android project
But, when I select my account
debug say

"android.view.WindowLeaked: Activity com.google.android.gms.auth.api.signin.internal.SignInHubActivity has leaked window DecorView@abb3dab[] that was originally added here"

How I solve this..?

**Comment by Pujolsluis** [comment]
Hey @JaeWLee, could you please describe a bit more your situation and how to replicate the error, also add your stacktrace to the post it would be really helpful, you can fill out this template to better describe the issue for us:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Pujolsluis** [comment]
Good Job @JaeWLee 😋, Yup permissions are an important part of the Android Setup Guide. I'm glad you got to resolve your issue. 💪
