### ISSUE TITLE
ActiveToken value is null, IsLoggedIn is false

### ISSUE THREAD

**Issue by JasonXtreme** [CrossGeeks/GoogleClientPlugin#43]
Using the library, calling either 
`var response = await CrossGoogleClient.Current.LoginAsync();`
or
`var response = await CrossGoogleClient.Current.SilentLoginAsync();`
opens the dialog when needed and results in the OnLogin event firing, a response with Status set to Completed, complete user data in the response object, yet the CrossGoogleClient.Current.ActiveToken property remains null, and CrossGoogleClient.Current.IsLoggedIn remains false (according to debugger).

Steps to reproduce:
Start application and call the above line of code, successfully login, check ActiveToken value.

Debug device:
Nexus 5 (Hammerhead) on stock lastest rom with up to date google services.

**Comment by Vahradrim** [comment]
I have the exact same issue... :(
I use the Plugin.Facebook and it works well, but with Plugin.Google "ActiveToken" is null and "IsLoggedIn" is false, but I do have my user information (and photo, etc...), but no Active Token

![ActiveTokenNull](https://user-images.githubusercontent.com/32706466/67625807-23491480-f843-11e9-9951-9304bd5c6034.png)

**Comment by Vahradrim** [comment]
Hi guys !
I found the solution by reading the documentation, it's not an issue : 
You just have to : 

Documentation :
[https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/GoogleClient/docs/GettingStarted.md#enabling-server-auth-code-or-requestidtoken-programmatically-optional](url)

**INSTRUCTIONS :**
1 - Go there : (at the end of the page follow "Get your backend server's OAuth 2.0 client ID")
[https://developers.google.com/identity/sign-in/android/start-integrating](url)

2 - Get the android and iOS "Web application" (in the second table), should look like : 
**Web client (auto created by Google Service)**
xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com

3 - In Android "MainActivity.cs" class
Instead of 
`GoogleClientManager.Initialize(this);`
Add 2 parameters : 
`string yourWebApplicationKey = "xxxxxxxxxxxx-x...x.apps.googleusercontent.com";`
`GoogleClientManager.Initialize(this, yourWebApplicationKey, yourWebApplicationKey);`

4 - In iOS do the same but be careful it's not the same key !
(At step 2, in my table I have the one generated under my android key, and the one under my iOS key)

And you're done ! 🥇 

Now, in the method "GoogleSignInSuccess", just do : 
`string userActiveToken = CrossGoogleClient.Current.ActiveToken;`

**Comment by JasonXtreme** [comment]
Who would've though I'd ignored the part I was missing. Nice catch.

**Comment by MalmoIt** [comment]
@Vahradrim Do I create a new OAuth Client ID with application type iOS and Android or two types of Web Application?

**Comment by maurosampietro** [comment]
I have this exact same problem, also noticed in #17 

By providing the web API key in `the GoogleClientManager.Initialize(this, webApiKey, webApiKey `  AccessToken gets assigned but still `IsLoggedIn = false`

Also, in google-services.json, my client node has more than 1 id, so i tried all of them but id do not really know which one should work.
```

"client": [
    {
      "client_info": {
        "mobilesdk_app_id": "",
        "android_client_info": {
          "package_name": ""
        }
      },
      "oauth_client": [
        {
          "client_id": "**THIS ONE**",
          "client_type": 1,
          "android_info": {
            "package_name": "",
            "certificate_hash": ""
          }
        },
        {
          "client_id": "**OR THIS ONE**",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": ""
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "**MAYBE THIS?**",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
```

If i close the app and reopen it, ActiveToken is null again.
Any help? FacebookLogin worked like a charm
